services:
  blog-db:
    container_name: blog-db
    image: postgres:17
    restart: always
    volumes:
      - ./blog-volumn:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
